# These are the variables in the current UCATS-B data file. The variable
# prefixes are defined in the config.yaml file.
#
# Aeris d1: 
#   P_mbars, T_gas, T_ambient, N2O_ppb, H2O_ppm, CO_ppb, T_TEC_Sink
# Aeris d2:
#   P_mbars, T_gas, T_ambient, Laser_PID_Readout, Det_PID_Readout, 
#   Ramp_Ampl, CO2_ppm, H2O_ppm, N2O_ppb, Power_Input_mV, 
#   T_FET, T_TEC, T_TEC_Sink, TEC_Power
# 2Btech Ozone:
#     oz_o3, oz_t, oz_p, oz_flow_a, oz_flow_b
# Maycomm: 
#     w_H2O_sh, w_H2O_B, w_H2O_lg, w_H2O_CD, w_p, w_t, w_t_elec, 
#     w_amp, w_pow, w_pos, w_zer, w_posB
#
##### To add additional plot windows, add a win# definition below with left and right axis
# variables. The code is currently limited to two variables per axis.

windows:
    win1:
        name: 'Cell Pressure'
        left_y: ['d1_P_mbars', 'd2_P_mbars']
    
    win2:
        name: 'Mole Fractions'
        left_y: ['d1_N2Oc_ppb', 'd2_N2Oc_ppb']
        right_y: ['d1_CO2c_ppm']
