triggers:
  alt_high: 500       # less than this mbar
  alt_low: 700        # greater than this mbar
  air_duration: 300   # time in S for air sampling
  cal_duration: 40    # time in S for cal sampling

telemetry:
  enable: true
  config: telem-config.yaml

devices:
  Aeris_CO2:
    inst_num: 2   # don't change this
    serial_port: /dev/ttyUSB0
    sim_mode: false
    data_var_prefix: d1_
    display_vars:
      - P_mbars
      - T_gas
      - T_ambient
      - T_TEC
      - Det_PID
      - N2Oc_ppb
      - CO2c_ppm

  Aeris_CO:
    inst_num: 1   # don't change this
    serial_port: /dev/ttyUSB3
    sim_mode: false
    data_var_prefix: d2_
    display_vars:
      - P_mbars
      - T_gas
      - T_ambient
      - T_TEC_Sink
      - blank
      - N2Oc_ppb
      - COc_ppb

  O3_sensor:
    serial_port: /dev/ttyUSB2
    sim_mode: false
    data_var_prefix: oz_
    display_vars:
      - o3best
      - t
      - p

  H2O_sensor:
    serial_port: /dev/ttyUSB1
    sim_mode: false
    data_var_prefix: w_
    display_vars:
      - H2Obest
      - H2O_sh
      - H2O_lg

  Labjack:
    # Labjack control
    # UCATS-B uses a T4 Labjack with 12 DIO, 4 A2D, and 2 DAC lines.
    # Digital I/O are on lines FIO0-FIO3, EIO0-EIO3, and CIO0-CIO3
    # Analog Input are on lines AIN0-AIN3
    # There are two 0-5V DACs addressed via DAC0 and DAC1
    sim_mode: false
    data_var_prefix: j_     # leave blank for no prefix
    display_vars:
      - pilot_power
      - P_cal0_low
      - P_cal0_hi
      - P_cal1_low
      - P_cal1_hi

    digouts:
      # variables used in instrument.py
      FIO4: 'sol_cals'
      FIO5: 'sol_aircal'
      FIO6: 'pilot_wd'
      FIO7: 'pumps'

    digins:
      # these addresses are read every second
      CIO0: 'pilot_power'

    analog:
      # read once a second
      # The list of numbers in cal are coefficients for a polynomial.
      # [intercept, slope, quadratic, etc.]
      AIN0:
        var: 'P_cal1_low'
        cal: [-14.338, 15.848]
      AIN1:
        var: 'P_cal1_hi'
        cal: [-57.6, 544]
      AIN2:
        var: 'P_cal0_low'
        cal: [-14.338, 15.848]
      AIN3:
        var: 'P_cal0_hi'
        cal: [-57.6, 544]
