triggers:
  alt_high: 700    # less than this mbar
  alt_low: 800   # greater than this mbar

devices:
  
  labjack:
    # Labjack control
    # UCATS-B uses a T4 Labjack with 12 DIO, 4 A2D, and 2 DAC lines.
    # Digital I/O are on lines FIO0-FIO3, EIO0-EIO3, and CIO0-CIO3
    # Analog Input are on lines AIN0-AIN3
    # There are two 0-5V DACs addressed via DAC0 and DAC1
    sim_mode: true
    data_var_prefix: j_     # leave blank for no prefix

    pilot_wd: 'FIO6'        # pilot watchdog
    #pilot_switch: 'FIO5'    # pilot on/off switch
    sol_cal: 'FIO4'         # solenoid for cal1 or cal2
    sol_aircal: 'FIO5'      # solenoid for air or cal selection
    pumps: 'FIO7'           # pumps on/off
    power_aerisCO2: 'EIO4'
    power_aerisCO: 'EIO6'
    display_vars:
      - pilot_power
      - temp1

    report:
      # report is used for data read and record from the labjack
      freq: 1  # seconds
      addresses:
        # Analog Input Configuration
        # The list of numbers in cal are coefficients for a polynomial.
        # [intercept, slope, quadratic, etc.]
        analog:
          0:
            var: 'amb_press'
            cal: [0, 1]  
          1:
            var: 'pump_speed'
            cal: [0, 10, 2]
          2:
            var: 'temp1'
            cal: [0, 1]
        digital:
          # Digital Input read
          CIO0:
            var: 'pilot_power'
          #EIO1: 
          #  var: 'digIN1' 

  aeris_CO2:
    inst_num: 2   # don't change this
    serial_port: /dev/ttyUSB0
    sim_mode: false
    data_var_prefix: d1_
    display_vars:
      - T_gas
      - T_ambient
      - N2O_ppb
      - CO2_ppm

  aeris_CO:
    inst_num: 1   # don't change this
    serial_port: /dev/ttyUSB2
    sim_mode: false
    data_var_prefix: d2_
    display_vars:
      - T_gas
      - T_ambient
      - N2O_ppb
      - CO_ppb
 
  o3_sensor:
    serial_port: /dev/ttyUSB1
    sim_mode: false
    data_var_prefix: oz_
    display_vars:
      - t
      - p
      - o3
   
  h2o_sensor:
    serial_port: /dev/ttyUSB1
    sim_mode: true
    data_var_prefix: w_
    display_vars:
      - H2O_sh
      - H2O_B
      - H2O_lg
   
