# data variables and IP info for the MTS system
mts:
  iwg_prefix: UCB
  ip: 10.11.96.10       # for lab tests
  # ip: 10.11.96.131    # for flight
  port: 7075
  rate: 1
  variables:
    - datetime
    - d1_CO2c_ppm
    - d1_N2Oc_ppb
    - d2_COc_ppb
    - d2_N2Oc_ppb
    - oz_o3best
    - w_H2Obest
    - oz_p
    - d1_T_gas
    - d2_T_gas

# data variables and IPs for data transmission to ground stations
data:
  iwg_prefix: UCBdata
  # list of ip address to send engineering data too.
  ip: [10.11.96.10, 10.11.96.11]    # for lab tests
  # for flight ..101. for Ellington use ..102. for elsewhere
  # ip: [10.16.101.145, 10.16.101.146, 10.16.101.147, 10.16.101.148]
  port: 50555
  rate: 1   # frequency to send in seconds
  variables:
    - datetime
    - d1_CO2c_ppm
    - d1_N2Oc_ppb
    - d2_COc_ppb
    - d2_N2Oc_ppb

    - d1_P_mbars
    - d1_T_gas
    - d1_T_ambient
    - d1_T_TEC
    - d1_T_TEC_Sink
    - d1_Det_PID
    - d1_Laser_PID
    - d1_Power_Input_mV
    - d1_T_FET

    - d2_P_mbars
    - d2_T_gas
    - d2_T_ambient
    - d2_T_TEC_Sink

    - j_P_cal0_low
    - j_P_cal0_hi
    - j_P_cal1_low
    - j_P_cal1_hi

    - oz_o3
    - oz_o3best
    - oz_t
    - oz_p

    - w_H2O_sh
    - w_H2O_B
    - w_H2O_lg
    - w_H2Obest
